apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: chronograf
    releaseName: chronograf
    includeCRDs: true
    apiVersions:
      - networking.k8s.io/v1/Ingress
    repo: https://helm.influxdata.com/
    valuesFile: values.yml
