apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yml

helmCharts:
  - name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    includeCRDs: true
    valuesFile: values.yml
