---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - namespace.yml

helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    includeCRDs: true

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/created-by: kustomizer
      app.kubernetes.io/name: proxy
