---
- name: Create SSH keys directory for Jenkins Agent
  file:
    path: "{{ service_keys_directory }}"
    state: directory
    mode: '0700'

- name: Generate SSH keys for Jenkins Agent if not exist
  community.crypto.openssh_keypair:
    path: "{{ service_keys_directory }}/id_ed25519"
    type: ed25519
    mode: '0600'

- name: Configure authorized_keys for Jenkins Agent
  copy:
    src: "{{ service_keys_directory }}/id_ed25519.pub"
    dest: "{{ service_keys_directory }}/authorized_keys"
    mode: '0644'
    remote_src: yes

- name: Set proper permissions for SSH keys directory
  file:
    path: "{{ service_keys_directory }}"
    recurse: yes
    mode: '0700'