apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - volume.yml
  - secrets.yml

helmCharts:
  - name: influxdb2
    releaseName: influxdb2
    includeCRDs: true
    apiVersions:
      - networking.k8s.io/v1/Ingress
    repo: https://helm.influxdata.com/
    valuesFile: values.yml
